name: Build and Test Project

on:
  push:
    branches: [ "master", "main" ]  # Trigger on pushes to master/main
  pull_request:
    branches: [ "master", "main" ]  # Trigger on pull requests to master/main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        options: --health-cmd="mysqladmin ping --silent" --health-timeout=5s --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: sohel@636172
          MYSQL_DATABASE: food_ordering_db
          MYSQL_USER: root
          MYSQL_PASSWORD: sohel@636172
        ports:
          - 3306:3306

    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java (for your Java + JDBC backend)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Wait for MySQL to be ready (allow MySQL to start)
      - name: Wait for MySQL to be ready
        run: |
          docker exec mysql mysqladmin --wait-for-all-databases --silent --user=root --password=rootpassword

      # Step 4: Build backend (Java + JDBC)
      - name: Build Backend (Java + JDBC)
        run: |
          javac -d bin src/*.java  # Modify if you have a different structure
          java -cp bin Main  # Run your main class to test the build

      # Step 5: Set up Node.js (for your React frontend)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 6: Install frontend dependencies
      - name: Install Frontend dependencies
        working-directory: frontend
        run: npm install

      # Step 7: Run frontend tests (if applicable)
      - name: Run Frontend Tests
        working-directory: frontend
        run: npm test

      # Optional: Step 8: Deploy (if needed)
      # - name: Deploy to production
      #   run: your-deployment-script.sh
